#!/usr/bin/env bash
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/config"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/common-functions"
source "$PLUGIN_BASE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/config/functions"
if [[ -f "$PLUGIN_AVAILABLE_PATH/docker-options/functions" ]]; then
  source "$PLUGIN_AVAILABLE_PATH/docker-options/functions"
fi

service_connect() {
  local SERVICE="$1"
  local SERVICE_ROOT="$PLUGIN_DATA_ROOT/$SERVICE"
  local SERVICE_NAME="$(get_service_name "$SERVICE")"
  local DATABASE_NAME="$(get_database_name "$SERVICE")"
  local PASSWORD="$(service_password "$SERVICE")"
  local SERVICE_TTY_OPTS
  has_tty && SERVICE_TTY_OPTS="-t"

  docker exec -i $SERVICE_TTY_OPTS "$SERVICE_NAME" mongo -u "$SERVICE" -p "$PASSWORD" --authenticationDatabase "$DATABASE_NAME" "$DATABASE_NAME"
}

service_create() {
  local SERVICE="$1"
  is_valid_service_name "$SERVICE" || dokku_log_fail "Please specify a valid name for the service. Valid characters are: [A-Za-z0-9_]+"
  [[ -z "$SERVICE" ]] && dokku_log_fail "Please specify a valid name for the service"
  [[ ! -d "$PLUGIN_DATA_ROOT/$SERVICE" ]] || dokku_log_fail "$PLUGIN_SERVICE service $SERVICE already exists"
  SERVICE_ROOT="$PLUGIN_DATA_ROOT/$SERVICE"
  LINKS_FILE="$SERVICE_ROOT/LINKS"

  service_parse_args "${@:2}"

  if ! service_image_exists "$SERVICE"; then
    if [[ "$PLUGIN_DISABLE_PULL" == "true" ]]; then
      dokku_log_warn "${PLUGIN_DISABLE_PULL_VARIABLE} environment variable detected. Not running pull command." 1>&2
      dokku_log_warn "   docker pull ${IMAGE}" 1>&2
      dokku_log_warn "$PLUGIN_SERVICE service creation failed"
      exit 1
    fi
    docker pull "$PLUGIN_IMAGE:$PLUGIN_IMAGE_VERSION" || dokku_log_fail "$PLUGIN_SERVICE image $PLUGIN_IMAGE:$PLUGIN_IMAGE_VERSION pull failed"
  fi

  mkdir -p "$SERVICE_ROOT" || dokku_log_fail "Unable to create service directory"
  mkdir -p "$SERVICE_ROOT/data" || dokku_log_fail "Unable to create service data directory"
  mkdir -p "$SERVICE_ROOT/logs" || dokku_log_fail "Unable to create service logs directory"
  mkdir -p "$SERVICE_ROOT/config" || dokku_log_fail "Unable to create service config directory"
  touch "$LINKS_FILE"

  ROOTPASSWORD=$(openssl rand -hex 16)
  PASSWORD=$(openssl rand -hex 16)
  if [[ -n "$SERVICE_PASSWORD" ]]; then
    PASSWORD="$SERVICE_PASSWORD"
    dokku_log_warn "Specified password may not be as secure as the auto-generated password"
  fi
  if [[ -n "$SERVICE_ROOT_PASSWORD" ]]; then
    ROOTPASSWORD="$SERVICE_ROOT_PASSWORD"
    dokku_log_warn "Specified root password may not be as secure as the auto-generated root password"
  fi
  echo "$ROOTPASSWORD" >"$SERVICE_ROOT/ROOTPASSWORD"
  echo "$PASSWORD" >"$SERVICE_ROOT/PASSWORD"
  chmod 640 "$SERVICE_ROOT/ROOTPASSWORD" "$SERVICE_ROOT/PASSWORD"

  [[ -n "$SERVICE_CUSTOM_ENV" ]] && NEO4J_CUSTOM_ENV="$SERVICE_CUSTOM_ENV"
  if [[ -n $NEO4J_CUSTOM_ENV ]]; then
    echo "$NEO4J_CUSTOM_ENV" | tr ';' "\n" >"$SERVICE_ROOT/ENV"
  else
    echo "" >"$SERVICE_ROOT/ENV"
  fi

  [[ -n "$PLUGIN_CONFIG_OPTIONS" ]] && MONGO_CONFIG_OPTIONS="$PLUGIN_CONFIG_OPTIONS"
  if [[ -n "$NEO4J_CONFIG_OPTIONS" ]]; then
    echo "$NEO4J_CONFIG_OPTIONS" >"$SERVICE_ROOT/NEO4J_CONFIG_OPTIONS"
  else
    echo "" >"$SERVICE_ROOT/NEO4J_CONFIG_OPTIONS"
  fi

  write_database_name "$SERVICE"
  service_create_container "$SERVICE"
}

service_create_container() {
  local SERVICE="$1"
  local SERVICE_ROOT="$PLUGIN_DATA_ROOT/$SERVICE"
  local SERVICE_HOST_ROOT="$PLUGIN_DATA_HOST_ROOT/$SERVICE"
  local SERVICE_NAME="$(get_service_name "$SERVICE")"
  local ROOTPASSWORD="$(service_root_password "$SERVICE")"
  local PASSWORD="$(service_password "$SERVICE")"
  local DATABASE_NAME="$(get_database_name "$SERVICE")"

  if [[ -f "$SERVICE_ROOT/NEO4J_CONFIG_OPTIONS" ]]; then
    export NEO4J_CONFIG_OPTIONS="$(cat "$SERVICE_ROOT/NEO4J_CONFIG_OPTIONS")"
  fi

  # shellcheck disable=SC2086
  ID=$(docker run --name "$SERVICE_NAME" -v "$SERVICE_HOST_ROOT/data:/data" -v "$SERVICE_HOST_ROOT/logs:/logs" --env-file="$SERVICE_ROOT/ENV" --env "NEO4J_AUTH=neo4j/$PASSWORD" -d --restart always --label dokku=service --label dokku.service=neo4j "$PLUGIN_IMAGE:$PLUGIN_IMAGE_VERSION" neo4j $NEO4J_CONFIG_OPTIONS)
  echo "$ID" >"$SERVICE_ROOT/ID"

  dokku_log_verbose_quiet "Waiting for container to be ready"
  docker run --rm --link "$SERVICE_NAME:$PLUGIN_COMMAND_PREFIX" dokku/wait:0.4.1 -p "$PLUGIN_DATASTORE_WAIT_PORT" >/dev/null

  # echo "db.createUser({user:'admin',pwd:'$ROOTPASSWORD',roles:[{role:'userAdminAnyDatabase',db:'admin'},{role:'__system',db:'admin'},{role:'root',db:'admin'}]})" | docker exec -i "$SERVICE_NAME" mongo admin >/dev/null
  # echo "db.createUser({user:'$SERVICE',pwd:'$PASSWORD',roles:[{role:'readWrite',db:'$DATABASE_NAME'}]})" | docker exec -i "$SERVICE_NAME" mongo -u admin -p "$ROOTPASSWORD" --authenticationDatabase admin "$DATABASE_NAME" >/dev/null
  dokku_log_info2 "$PLUGIN_SERVICE container created: $SERVICE"
  service_info "$SERVICE"
}

service_export() {
  local SERVICE="$1"
  local SERVICE_ROOT="$PLUGIN_DATA_ROOT/$SERVICE"
  local SERVICE_NAME="$(get_service_name "$SERVICE")"
  local DATABASE_NAME="$(get_database_name "$SERVICE")"
  local PASSWORD="$(service_password "$SERVICE")"
  local SERVICE_HOST_ROOT="$PLUGIN_DATA_HOST_ROOT/$SERVICE"

  # dokku_log_warn "Stopping database neo4j"
  # the following can be used with enterprise version, instead of stopping the container
  # docker exec "$SERVICE_NAME" bash cypher-shell -u neo4j -p "$PASSWORD" -d system "STOP DATABASE neo4j;" >/dev/null 2>/dev/null

  service_stop "$SERVICE" >/dev/null 2>/dev/null
  
  [[ -n $SSH_TTY ]] && stty -opost
  # the following can be used with enterprise version, instead of spinning up new container 
  # docker exec "$SERVICE_NAME" bash -c "neo4j-admin dump --database=neo4j --to=- 2>error2.txt"
  docker run --entrypoint="/bin/bash" -v "$SERVICE_HOST_ROOT/data:/data" -v "$SERVICE_HOST_ROOT/logs:/logs" --env-file="$SERVICE_ROOT/ENV" --env "NEO4J_AUTH=neo4j/$PASSWORD" "$PLUGIN_IMAGE:$PLUGIN_IMAGE_VERSION" -c "neo4j-admin dump --database=neo4j --to=- 2>error2.txt"

  status=$?
  [[ -n $SSH_TTY ]] && stty opost
  
  # dokku_log_warn "Starting database neo4j"
  service_start "$SERVICE" >/dev/null 2>/dev/null

  # docker exec "$SERVICE_NAME" bash cypher-shell -u neo4j -p "$PASSWORD" -d system "START DATABASE neo4j;" >/dev/null 2>/dev/null
  
  exit $status
}

service_import() {
  local SERVICE="$1"
  local SERVICE_ROOT="$PLUGIN_DATA_ROOT/$SERVICE"
  local SERVICE_HOST_ROOT="$PLUGIN_DATA_HOST_ROOT/$SERVICE"
  local SERVICE_NAME="$(get_service_name "$SERVICE")"
  local DATABASE_NAME="$(get_database_name "$SERVICE")"
  local PASSWORD="$(service_password "$SERVICE")"

  if [[ -t 0 ]]; then
    dokku_log_fail "No data provided on stdin."
  fi

  # A database needs to be stopped before a dump can be made
  # the following can be used with enterprise version, instead of stopping the container
  # docker exec "$SERVICE_NAME" bash cypher-shell -u neo4j -p "$PASSWORD" -d system "STOP DATABASE neo4j;" 
  service_stop "$SERVICE" 
  
  
  dokku_log_verbose_quiet "Loading data into neo4j container"
  # Run as --user neo4j otherwise te database is made as root and you get AccessDenied error
  # see https://community.neo4j.com/t/database-offline-and-will-not-restart/27914/5 
  # --from=- means load from stdin
  # command for enteprise version:
  # docker exec --user neo4j -i "$SERVICE_NAME" bash -c "neo4j-admin load --database=neo4j --force --from=-"
  # -i for reading from stdin
  docker run --user neo4j --entrypoint="/bin/bash" -i -v "$SERVICE_HOST_ROOT/data:/data" -v "$SERVICE_HOST_ROOT/logs:/logs" --env-file="$SERVICE_ROOT/ENV" --env "NEO4J_ACCEPT_LICENSE_AGREEMENT=yes" --env "NEO4J_AUTH=neo4j/$PASSWORD" "$PLUGIN_IMAGE:$PLUGIN_IMAGE_VERSION" -c "neo4j-admin load --database=neo4j --force --from=-"   

  # start service again
  service_start "$SERVICE" 
  #docker exec "$SERVICE_NAME" bash cypher-shell -u neo4j -p "$PASSWORD" -d system "START DATABASE neo4j;" 
}

service_start() {
  local SERVICE="$1"
  local QUIET="$2"
  local SERVICE_ROOT="$PLUGIN_DATA_ROOT/$SERVICE"
  local SERVICE_NAME="$(get_service_name "$SERVICE")"
  local ID=$(docker ps -aq --no-trunc --filter "status=running" --filter "name=^/$SERVICE_NAME$" --format '{{ .ID }}') || true
  if [[ -n $ID ]]; then
    [[ -z $QUIET ]] && dokku_log_warn "Service is already started"
    if [[ ! -f "$SERVICE_ROOT/ID" ]] || [[ "$(cat "$SERVICE_ROOT/ID")" != "$ID" ]]; then
      [[ -z $QUIET ]] && dokku_log_warn "Updating local container ID"
      echo "$ID" >"$SERVICE_ROOT/ID"
    fi
    return 0
  fi

  dokku_log_info2_quiet "Starting container"
  local PREVIOUS_ID=$(docker ps -aq --no-trunc --filter "status=exited" --filter "name=^/$SERVICE_NAME$" --format '{{ .ID }}') || true
  local ROOTPASSWORD="$(service_root_password "$SERVICE")"
  local PASSWORD="$(service_password "$SERVICE")"

  if [[ -n $PREVIOUS_ID ]]; then
    docker start "$PREVIOUS_ID" >/dev/null
    service_port_unpause "$SERVICE"
    dokku_log_info2 "Container started"
  elif service_image_exists "$SERVICE" && [[ -n "$ROOTPASSWORD" ]] && [[ -n "$PASSWORD" ]]; then
    service_create_container "$SERVICE"
  else
    dokku_log_verbose_quiet "Neither container nor valid configuration exists for $SERVICE"
  fi
}

service_url() {
  local SERVICE="$1"
  local SERVICE_DNS_HOSTNAME="$(service_dns_hostname "$SERVICE")"
  local DATABASE_NAME="$(get_database_name "$SERVICE")"
  local PASSWORD="$(service_password "$SERVICE")"
  echo "$PLUGIN_SCHEME://$SERVICE_DNS_HOSTNAME:${PLUGIN_DATASTORE_PORTS[0]}"
}
